project:
  type: website
  output-dir: docs

website:
  title: "Analítica y Visualización de Datos, Aplicaciones"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - Docente.qmd

format:
  html:
    theme: 
      light: flatly
      dark: [darkly, theme-dark.scss]
    

editor: visual

