project:
  type: website
  output-dir: docs

website:
  title: "Analítica y Visualización de Datos, Aplicaciones"
  repo-url: https://github.com/roammi/data_analytics_and_viz_module
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - Docente.qmd

format:
  html:
    theme: 
      light: flatly
      dark: [darkly, theme-dark.scss]
    toc: true
    toc-title: "En esta página"
    

editor: visual

