project:
  type: website
  output-dir: docs

website:
  title: "Analítica y Visualización de Datos, Aplicaciones"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: flatly
      dark: [darkly, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual

